version: '3.1'

services:

  postgres:
    container_name: docker_postgres
    networks:
      - gateway
    #expose:
    #  - 5432
    ports:
      - "5432:5432"
    hostname: postgres
    image: postgres:alpine
    env_file:
      - database.env # configure postgres
    volumes:
      - ./data/db:/data/db # persist data even if container shuts down

  spring:
    build: .
    container_name: docker_spring
    networks:
      - gateway
    ports:
      - "8080:8080"
    hostname: spring
    depends_on:
      - postgres

networks:
  gateway:
    driver: "bridge"

volumes:
  postgres-data: # named volumes can be managed easier using docker-compose