version: '3.4'

services:

  postgres:
    container_name: docker_postgres
    networks:
      - gateway
    expose:
      - 5432
    #ports:
    #  - "5432:5432"
    #hostname: postgres # unsure if needed
    image: postgres:alpine
    env_file:
      - database.env # configure postgres
    volumes:
      - type: volume
        source: postgres-data
        # note: this target is the default target of the postgres image for creating an anonymous volume
        # if we specify a different target, postgres will still create an anonymous volume every run and NOT
        # save into our named volume
        target: /var/lib/postgresql/data

  spring:
    build: .
    container_name: docker_spring
    networks:
      - gateway
    ports:
      - "8080:8080"
    #hostname: spring # unsure if needed
    depends_on:
      - postgres

networks:
  gateway:
    driver: "bridge"

# top-level volumes key for named volumes. necessary when multiple services access the same volume
# not our case here, but let's still leave it as it is
volumes:
  postgres-data: # named volumes can be managed easier using docker-compose